package {
import flash.display.Sprite;

public class EulerProblem2 extends Sprite {
    public function EulerProblem2() {
        super();

        /*
        Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

        By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
        */

        var a:Number = 0;
        var b:Number = 1;
        var c:Number = 0;

        var result:Number = 0;

        while (a < 4000000) {
            a = b + c;
            if(a % 2 == 0) result += a;
            c = b;
            b = a;
        }

        trace("Result: " + result);
    }
}
}